#!/usr/bin/env python3
"""Build a clean Yapply plugin bundle from the source checkout."""

from __future__ import annotations

import argparse
import shutil
import sys
import tempfile
import zipfile
from pathlib import Path


SOURCE_ROOT = Path(__file__).resolve().parents[1]
INCLUDED_DIRECTORIES = (
    ".claude-plugin",
    ".codex-plugin",
    "assets",
    "bin",
    "docs",
    "schemas",
    "skills",
)
INCLUDED_FILES = ("LICENSE", "PRIVACY.md", "README.md", "requirements.txt")
BUNDLE_MARKER = ".yapply-plugin-bundle"


def copy_bundle(destination: Path, force: bool = False) -> Path:
    destination = destination.expanduser().resolve()
    if destination.name != "yapply" or destination == SOURCE_ROOT:
        raise ValueError("Output must be a dedicated directory named 'yapply', such as dist/yapply")
    if destination.exists() or destination.is_symlink():
        if not force:
            raise FileExistsError(f"{destination} already exists; pass --force to replace it")
        if destination.is_symlink():
            destination.unlink()
        elif destination.is_dir() and (destination / BUNDLE_MARKER).is_file():
            shutil.rmtree(destination)
        else:
            raise ValueError(
                f"Refusing to replace unmarked path {destination}; it is not a Yapply build bundle"
            )

    destination.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix=".yapply-build-", dir=destination.parent) as temp_dir:
        staging = Path(temp_dir) / "yapply"
        staging.mkdir()
        for directory in INCLUDED_DIRECTORIES:
            shutil.copytree(
                SOURCE_ROOT / directory,
                staging / directory,
                ignore=shutil.ignore_patterns("__pycache__", "*.pyc", ".DS_Store"),
            )
        scripts = staging / "scripts"
        scripts.mkdir()
        shutil.copy2(SOURCE_ROOT / "scripts" / "yapply.py", scripts / "yapply.py")
        for filename in INCLUDED_FILES:
            shutil.copy2(SOURCE_ROOT / filename, staging / filename)
        (staging / BUNDLE_MARKER).write_text("generated by scripts/build_plugin.py\n", encoding="utf-8")
        staging.rename(destination)

    forbidden = (".git", ".yapply", "tests", "tmp", "output", "__pycache__")
    leaked = [name for name in forbidden if (destination / name).exists()]
    if leaked:
        raise RuntimeError("Bundle contains excluded paths: " + ", ".join(leaked))
    return destination


def write_upload_zip(bundle: Path, archive: Path, force: bool = False) -> Path:
    """Zip a built bundle for the OpenAI Plugins Directory, plugin root at the archive root.

    The Claude manifest and the build marker stay out: Claude's directory reads the
    GitHub repository instead, and OpenAI reads `.codex-plugin/plugin.json`.
    """
    archive = archive.expanduser().resolve()
    if archive.suffix != ".zip":
        raise ValueError("--zip must name a .zip file")
    if archive.exists() and not force:
        raise FileExistsError(f"{archive} already exists; pass --force to replace it")
    left_out = {".claude-plugin", BUNDLE_MARKER}
    archive.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(archive, "w", zipfile.ZIP_DEFLATED) as handle:
        for path in sorted(bundle.rglob("*")):
            relative = path.relative_to(bundle)
            if path.is_file() and relative.parts[0] not in left_out:
                handle.write(path, relative.as_posix())
    return archive


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=SOURCE_ROOT / "dist" / "yapply",
        help="Bundle directory (default: dist/yapply)",
    )
    parser.add_argument(
        "--zip",
        type=Path,
        help="Also write the OpenAI Plugins Directory upload, such as dist/yapply-openai.zip",
    )
    parser.add_argument("--force", action="store_true", help="Replace an existing bundle")
    args = parser.parse_args(argv)
    try:
        output = copy_bundle(args.output, args.force)
        archive = write_upload_zip(output, args.zip, args.force) if args.zip else None
    except (FileExistsError, ValueError, RuntimeError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    print(f"Built clean plugin bundle at {output}")
    if archive:
        print(f"Wrote OpenAI upload at {archive}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
